### ISSUE TITLE
RankNet code

### ISSUE THREAD

**Issue by Linkney** [houchenyu/L2R#3]
Maybe there is a mistake in [split_pair(order_pairs)] Function, relevant_doc and irrelecant_doc do not move while qid increasing, it seems d1 and d2 always swing in the first part of the training_data. I think it might be add #code like below.
```Python
def split_pairs(order_pairs):
    """
    split the pairs into two list, named relevant_doc and irrelevant_doc.
    relevant_doc[i] is prior to irrelevant_doc[i]
    :param order_pairs: ordered pairs of all queries
    :return: relevant_doc and irrelevant_doc
    """
    relevant_doc = []
    irrelevant_doc = []
    # addindex = 0
    query_num = len(order_pairs)
    for i in range(query_num):
        pair_num = len(order_pairs[i])
        for j in range(pair_num):
            d1, d2 = order_pairs[i][j]
            # d1 = d1 + addindex
            # d2 = d2 + addindex
            relevant_doc.append(d1)
            irrelevant_doc.append(d2)
        # addindex = addindex + pair_num
    return relevant_doc, irrelevant_doc
```

**Comment by houchenyu** [comment]
> Maybe there is a mistake in [split_pair(order_pairs)] Function, relevant_doc and irrelecant_doc do not move while qid increasing, it seems d1 and d2 always swing in the first part of the training_data. I think it might be add #code like below.
> 
> ```python
> def split_pairs(order_pairs):
>     """
>     split the pairs into two list, named relevant_doc and irrelevant_doc.
>     relevant_doc[i] is prior to irrelevant_doc[i]
>     :param order_pairs: ordered pairs of all queries
>     :return: relevant_doc and irrelevant_doc
>     """
>     relevant_doc = []
>     irrelevant_doc = []
>     # addindex = 0
>     query_num = len(order_pairs)
>     for i in range(query_num):
>         pair_num = len(order_pairs[i])
>         for j in range(pair_num):
>             d1, d2 = order_pairs[i][j]
>             # d1 = d1 + addindex
>             # d2 = d2 + addindex
>             relevant_doc.append(d1)
>             irrelevant_doc.append(d2)
>         # addindex = addindex + pair_num
>     return relevant_doc, irrelevant_doc
> ```

Thanks for your correction. There is a bug if I don't update the base index of docs. However, adding pair_num will arise the `out of index` error since the `pair_num` can't reflect the actual number of docs for each query. Instead of adding `pair_num`, I use another parameter to obtain the base index of docs. I have modified my code as follow:
```
def split_pairs(order_pairs, true_scores):

    relevant_doc = []
    irrelevant_doc = []
    doc_idx_base = 0
    query_num = len(order_pairs)
    for i in range(query_num):
        pair_num = len(order_pairs[i])
        docs_num = len(true_scores[i])
        for j in range(pair_num):
            d1, d2 = order_pairs[i][j]
            d1 += doc_idx_base 
            d2 += doc_idx_base 
            relevant_doc.append(d1)
            irrelevant_doc.append(d2)
        doc_idx_base += docs_num
    return relevant_doc, irrelevant_doc
```
You can check my lastest version of the code after updating.
